### ISSUE TITLE
RendererDecorator class should implement RenderableInterface

### ISSUE THREAD

**Issue by adayth** [domnikl/DesignPatternsPHP#267] opened 2017-02-22 23:28 UTC
RendererDecorator.php has this comment but it dosen't implements the interface.

```php
/**
 * the Decorator MUST implement the RendererInterface contract, this is the key-feature
 * of this design pattern. If not, this is no longer a Decorator but just a dumb
 * wrapper.
 */
abstract class RendererDecorator {}
```

**Comment by ihor** [comment] 2017-03-01 23:48
Funny thing that in my GoF book there is a mention that another name for ```Decorator``` is ```Wrapper``` :)

Anyway, I think forcing the interface is a useful thing but PHP allows us to simplify ```Decorator``` implementation in a case which is not present in this repo. Current implementation shows only one limited use case of ```Decorator``` pattern and is not showing the all fun stuff you can do.

<img width="682" alt="decorator" src="https://cloud.githubusercontent.com/assets/490943/23486249/75d6ecc8-fedf-11e6-972e-2fc282a58e4a.png">

This is a picture from my GoF book and as you can see this repo shows us only the ```BorderDecorator``` example (which is not actually true because ```BorderDecorator``` adds a new state and the implementation in this repo only decorates the existing behavior). 

But with ```Decorator``` not only you can decorate the existing behavior but also add a new one. Like in ```ScrollDecorator``` adds ```ScrollTo``` method which is not present in the decorated object. 

And as you can see in this case it is much easier to proxy method calls to the decorated object using magic ```__call``` method than using an interface.

So my suggestion is to change the whole ```Decorator``` example. I would make a PR but I don't have much time now. But maybe later if @domnikl agrees with what I said above.

**Comment by adayth** [comment] 2017-03-02 23:11
Sounds interesting to me @ihor maybe you can do something fast in a gist, as example. 
Homever, PHP magic methods generally are considered a bad practice, so I think that the implementation could be more clean without them.

**Comment by ihor** [comment] 2017-03-03 01:16
It is a trade-off: benefits of using an interface on one side and simpler implementation on another. 

Nobody complains about using magic methods in ```Proxy``` pattern implementation in PHP. As well as nobody complains about using magic methods in Python. It is a powerful concept which allows us to have write simpler code when used appropriately. 

I'll think about some nice example which would make sense in PHP. I tried to Google for good examples quickly but it is really hard since most of the examples are the same as in this repo (caused by the language limitations). A couple of links where you can see what I'm talking about:
- http://advancedcppwithexamples.blogspot.com/2010/09/c-example-for-decorator-design-pattern.html
- https://github.com/ezimuel/PHP-design-patterns/blob/master/Decorator.php

**Comment by adayth** [comment] 2017-03-06 19:19
The second example (the github link) seems good to me.

**Comment by domnikl** [comment] 2017-03-09 18:49
@ihor I agree, but could we not just extend the example and let `RendererDecorator` implement `RenderableInterface` and add some additional behavior to `JsonRenderer` like a method `formatOutput()`? Anyway, whenever you got some time, send me a PR and I will have a look.

**Comment by ihor** [comment] 2017-03-09 19:33
@domnikl sure, it should implement an interface in this example.

**Comment by andrewnester** [comment] 2017-04-04 12:02
Hi @domnikl @ihor @adayth !
I've just added PR to fix this issue.

**Comment by piotrgradzinski** [comment] 2018-07-10 15:01
Since the PR is merged and I can't see any other things to discuss I am closing this issue.

**Closed by piotrgradzinski** 2018-07-10 15:01 UTC
